package se.gui;

import se.controls.Controller;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nikki
 */
public class GameGUI extends javax.swing.JFrame {

    /**
     * Creates new form CognitionTest
     */
    public GameGUI() {
        initComponents();
    }

    private static final Controller inf = new Controller();
    //private 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jpUpper = new javax.swing.JPanel();
        jlblIntro = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jtfUsername = new javax.swing.JTextField();
        jlblWelcome = new javax.swing.JLabel();
        jlblWarning = new javax.swing.JLabel();
        jpMain = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        btnPeek = new javax.swing.JButton();
        jlblIcon = new javax.swing.JLabel();
        closed2 = new javax.swing.JLabel();
        closed3 = new javax.swing.JLabel();
        closed4 = new javax.swing.JLabel();
        closed5 = new javax.swing.JLabel();
        closed6 = new javax.swing.JLabel();
        totalCount = new javax.swing.JLabel();
        peekCount = new javax.swing.JLabel();
        searchCount = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblPeek = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jmenuNew = new javax.swing.JMenuItem();
        jmenu_exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Schematic Explanations for Robot Navigation and Action");
        setBackground(new java.awt.Color(0, 102, 102));
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpUpper.setBackground(new java.awt.Color(204, 255, 255));
        jpUpper.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblIntro.setText("Intro/Description ...");
        jpUpper.add(jlblIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 35, -1, -1));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jpUpper.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1261, 85, -1, -1));
        jpUpper.add(jtfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1188, 59, 138, -1));

        jlblWelcome.setText("Welcome!");
        jpUpper.add(jlblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1188, 35, 138, -1));
        jpUpper.add(jlblWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(933, 55, 249, 24));

        getContentPane().add(jpUpper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 750));

        jpMain.setBackground(new java.awt.Color(0, 102, 102));
        jpMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jpMain.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        btnPeek.setText("Peek");
        btnPeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeekActionPerformed(evt);
            }
        });
        jpMain.add(btnPeek, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jlblIcon.setText("jLabel1");
        jpMain.add(jlblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 340, 170));

        closed2.setText("jLabel1");
        jpMain.add(closed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 340, 170));

        closed3.setText("jLabel1");
        jpMain.add(closed3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, 340, 170));

        closed4.setText("jLabel1");
        jpMain.add(closed4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 340, 170));

        closed5.setText("jLabel1");
        jpMain.add(closed5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 340, 170));

        closed6.setText("jLabel1");
        closed6.setToolTipText("");
        jpMain.add(closed6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 350, 340, 170));

        totalCount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalCount.setText("Total Count:");
        jpMain.add(totalCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 620, -1, -1));

        peekCount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        peekCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        peekCount.setText("Peek Count:");
        jpMain.add(peekCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 560, -1, -1));

        searchCount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        searchCount.setText("Search Count:");
        jpMain.add(searchCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 590, -1, -1));

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("0");
        jpMain.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 620, 30, -1));

        lblPeek.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPeek.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPeek.setText("0");
        jpMain.add(lblPeek, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 560, 30, -1));

        lblSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSearch.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSearch.setText("0");
        jpMain.add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 590, 30, -1));

        getContentPane().add(jpMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1370, 670));

        jMenu.setText("File");

        jmenuNew.setText("New Game");
        jmenuNew.setToolTipText("");
        jmenuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuNewActionPerformed(evt);
            }
        });
        jMenu.add(jmenuNew);

        jmenu_exit.setText("Exit");
        jmenu_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_exitActionPerformed(evt);
            }
        });
        jMenu.add(jmenu_exit);

        jMenuBar.add(jMenu);

        setJMenuBar(jMenuBar);

        setSize(new java.awt.Dimension(1382, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    public JButton getBtnSubmit() {
        return btnSubmit;
    }

    private void jmenu_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmenu_exitActionPerformed

    private void jmenuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuNewActionPerformed
        inf.reset();
    }//GEN-LAST:event_jmenuNewActionPerformed

    private void btnPeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeekActionPerformed
        inf.peek();
    }//GEN-LAST:event_btnPeekActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        inf.search();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        inf.startGame();
    }//GEN-LAST:event_btnSubmitActionPerformed

    public JButton getBtnPeek() {
        return btnPeek;
    }

    public JButton getBtnSearch() {
        return btnSearch;
    }

    public JLabel getJlblWarning() {
        return jlblWarning;
    }

    public JLabel getJlblWelcome() {
        return jlblWelcome;
    }

    public JPanel getJpMain() {
        return jpMain;
    }

    public JPanel getJpUpper() {
        return jpUpper;
    }

    public JTextField getJtfUsername() {
        return jtfUsername;
    }

    //dispay peek count
    public JLabel getLblPeek() {
        return lblPeek;
    }

    //display search count
    public JLabel getLblSearch() {
        return lblSearch;
    }

    //display total count
    public JLabel getLblTotal() {
        return lblTotal;
    }

    public JLabel getJlblIcon() {
        return jlblIcon;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPeek;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel closed2;
    private javax.swing.JLabel closed3;
    private javax.swing.JLabel closed4;
    private javax.swing.JLabel closed5;
    private javax.swing.JLabel closed6;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JLabel jlblIcon;
    private javax.swing.JLabel jlblIntro;
    private javax.swing.JLabel jlblWarning;
    private javax.swing.JLabel jlblWelcome;
    private javax.swing.JMenuItem jmenuNew;
    private javax.swing.JMenuItem jmenu_exit;
    private javax.swing.JPanel jpMain;
    private javax.swing.JPanel jpUpper;
    private javax.swing.JTextField jtfUsername;
    private javax.swing.JLabel lblPeek;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel peekCount;
    private javax.swing.JLabel searchCount;
    private javax.swing.JLabel totalCount;
    // End of variables declaration//GEN-END:variables
}
